### ISSUE TITLE
Enhancement : req from straighten

### ISSUE THREAD

**Issue by RCura** [hrbrmstr/curlconverter#2]
Currently, with a defined curl string, you can either turn it into a "readable" R object with `straighten()`, or into a httr request with `make_req()`.

Those two function don't work together : they both use the same argument, that is the curl request string.

We should have a function that takes the `straighten()` result as input, and creates a request, just like `make_req()` does with plain string curl.

If straighten result can't be used again for a request, I can't understand its point.

**Comment by hrbrmstr** [comment]
That's a good idea. The thought was to have a function which folks could
get the parts in list form to inspect. I'll ponder what a revised
architecture might look like.

-Bob

**Comment by RCura** [comment]
My point is that I have to "craft" curl request in R, i.e. take a curl request and edit it before executing it.
I thought curlconverter would allow me to do this easily using `straighten()` so as to have the parts of the request in a structured form, edit some of the parts (for example the url, keeping the cookies), and then execute it.

Right now, to do this, I would have to do some nasty string handling in R, and `curlconverter` seems like a very nice way to ease this workflow :smile:

**Comment by brudis-r7** [comment]
Well, the other function spits out such a beast in text form :-) The original driver for this was to make it easier to answer some StackOverflow questions, but I can see it has more utility. I'm rly glad you poked at this since it'll really help make the pkg usable to a wide audience.

**Comment by RCura** [comment]
Seems to work like a charm with your latest commit. Thanks a lot, will try this on real data asap ! Kudos for the amazing work !

**Comment by hrbrmstr** [comment]
thx. keep the suggestions coming!
