### ISSUE TITLE
Complex curl statement generates an error with straighten()

### ISSUE THREAD

**Issue by smach** [hrbrmstr/curlconverter#20]
This curl statement works in my terminal

    curl -X POST https://api.jwplayer.com/v2/sites/MYAPIKEY/analytics/queries/ -H 'Authorization: MYAPISECRET' -H 'Content-Type: application/json' -d '{"start_date" : "2018-08-01", "end_date" : "2018-08-20", "dimensions" : ["media_id"], "metrics" : [{"operation": "sum", "field": "plays"}], "sort" : [{"field" : "plays", "order": "DESCENDING"}]}'

but when I try running straighten() on it

    straighten("curl -X POST https://api.jwplayer.com/v2/sites/MYAPIKEY/analytics/queries/ -H 'Authorization: MYSECRET' -H 'Content-Type: application/json' -d '{\"start_date\" : \"2018-08-01\", \"end_date\" : \"2018-08-20\", \"dimensions\" : [\"media_id\"], \"metrics\" : [{\"operation\": \"sum\", \"field\": \"plays\"}], \"sort\" : [{\"field\" : \"plays\", \"order\": \"DESCENDING\"}]}'")

I receive an error

    Error in parse_shorts(tokens, optionlist) : 
      -dis specified ambiguously 2 times

Is there something I need to do with those nested metrics and sort arguments? Thanks.

**Comment by hrbrmstr** [comment]
I _believe_ I corrected my error in the curl cmdline spec, but give this a go IRL and def re-open the issue if it still persists. Many thanks for reporting it!

**Comment by smach** [comment]
Thanks very much! The error is gone! I have another issue, but I suspect this may not be a curlconverter issue. I get this warning when I run make_req() on the straightened curl command:

    NOTE: 'json' encoding found in cURL request. docopt is known tostrip quotes from cURL parameterss. The httr 'body' parameter may needmanual intervention. You can review the 'orig_curl' list member of the`straighten()`ed object to compare the input to the parsed output.

Not sure what manual intervention I'd do here.

I suspect I may have to just run this particular complex curl command from my terminal. toJSON() shows

    "message": "Request body contains invalid JSON: 'Expecting property name enclosed in double quotes: line 1 column 2 (char 1)'."
