### ISSUE TITLE
Improve the readability of the README

### ISSUE THREAD

**Issue by patperu** [hrbrmstr/curlconverter#3]
Hello,
really nice development! 
Maybe a small change would increase the readability of the README:
 - If you change the 'deviceid' in this [curl_line](https://github.com/hrbrmstr/curlconverter/blame/09e4de7b1b96eed540b96eff841fb312fb3dc2c7/README.Rmd#L92) from '1' to '65'. This reduce the number of measures from 68 to 4. 

BTW I did this in the branch 'as_text' in my fork, but now I'm out off sync and don't know how to update the branch without a rebase... :confused:

**Comment by hrbrmstr** [comment]
great suggestions #ty!
