### ISSUE TITLE
`--user` Flag not interpreted in `straighten`

### ISSUE THREAD

**Issue by rentrop** [hrbrmstr/curlconverter#8]
When trying to convert a authentification flag like 

```
cURL <- 'curl --user name:password https://httpbin.org/basic-auth/name/password'
httr_call <- make_req(straighten(cURL))
```

`httr_call` looks as follows:

```
> httr_call
[[1]]
function () 
httr::VERB(verb = "GET", url = "https://httpbin.org/basic-auth/name/password")
<environment: 0x103ce1ca8>
```

Is it by design that the `--user` flag is not interpreted?

**Comment by hrbrmstr** [comment]
try the github/devel version. it should work now. the js lib I'm using did not handle them but I hacked it into the js lib earlier this week.

**Comment by rentrop** [comment]
Thats perfect, thanks

**Comment by hrbrmstr** [comment]
cool. glad it helps!
